name: Ray Tracer CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow running the workflow manually
  workflow_dispatch:

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    name: verilator-tests
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies 
        run: |
          sudo apt install cmake ninja-build verilator git pkg-config
          git clone "https://github.com/google/googletest"
      - name: Compile Google Test
        working-directory: ${{github.workspace}}/googletest
        run: |
          cmake -B build -GNinja -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_BUILD_TYPE=Release
          sudo ninja -C build install
      - name: Configure CMake
        run: |
          cmake -B ${{github.workspace}}/build -G Ninja
        # Build with a nice ninja status line
      - name: Build
        working-directory: ${{github.workspace}}/build
        run: |
          NINJA_STATUS="%p [%f:%s/%t] %o/s, %es" ninja
      - name: Test
        working-directory: ${{github.workspace}}/build
        run: |
          ctest --output-on-failure -j 4